package com.hhips.dao.mapper.problem;

import com.hhips.dao.model.problem.Paperproblem;
import com.hhips.dao.model.problem.PaperproblemExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PaperproblemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paperproblem
     *
     * @mbg.generated Thu May 31 15:35:41 CST 2018
     */
    long countByExample(PaperproblemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paperproblem
     *
     * @mbg.generated Thu May 31 15:35:41 CST 2018
     */
    int deleteByExample(PaperproblemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paperproblem
     *
     * @mbg.generated Thu May 31 15:35:41 CST 2018
     */
    int deleteByPrimaryKey(Integer paperproblemid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paperproblem
     *
     * @mbg.generated Thu May 31 15:35:41 CST 2018
     */
    int insert(Paperproblem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paperproblem
     *
     * @mbg.generated Thu May 31 15:35:41 CST 2018
     */
    int insertSelective(Paperproblem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paperproblem
     *
     * @mbg.generated Thu May 31 15:35:41 CST 2018
     */
    List<Paperproblem> selectByExample(PaperproblemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paperproblem
     *
     * @mbg.generated Thu May 31 15:35:41 CST 2018
     */
    Paperproblem selectByPrimaryKey(Integer paperproblemid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paperproblem
     *
     * @mbg.generated Thu May 31 15:35:41 CST 2018
     */
    int updateByExampleSelective(@Param("record") Paperproblem record, @Param("example") PaperproblemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paperproblem
     *
     * @mbg.generated Thu May 31 15:35:41 CST 2018
     */
    int updateByExample(@Param("record") Paperproblem record, @Param("example") PaperproblemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paperproblem
     *
     * @mbg.generated Thu May 31 15:35:41 CST 2018
     */
    int updateByPrimaryKeySelective(Paperproblem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paperproblem
     *
     * @mbg.generated Thu May 31 15:35:41 CST 2018
     */
    int updateByPrimaryKey(Paperproblem record);

    List<Paperproblem> selectByPaperID(Integer paperid);
}