package com.hhips.dao.mapper.problem;

import com.hhips.dao.model.problem.Problem;
import com.hhips.dao.model.problem.ProblemExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProblemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table problem
     *
     * @mbg.generated Mon Apr 30 14:26:05 CST 2018
     */
    long countByExample(ProblemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table problem
     *
     * @mbg.generated Mon Apr 30 14:26:05 CST 2018
     */
    int deleteByExample(ProblemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table problem
     *
     * @mbg.generated Mon Apr 30 14:26:05 CST 2018
     */
    int deleteByPrimaryKey(Integer idproblem);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table problem
     *
     * @mbg.generated Mon Apr 30 14:26:05 CST 2018
     */
    int insert(Problem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table problem
     *
     * @mbg.generated Mon Apr 30 14:26:05 CST 2018
     */
    int insertSelective(Problem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table problem
     *
     * @mbg.generated Mon Apr 30 14:26:05 CST 2018
     */
    List<Problem> selectByExample(ProblemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table problem
     *
     * @mbg.generated Mon Apr 30 14:26:05 CST 2018
     */
    Problem selectByPrimaryKey(Integer idproblem);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table problem
     *
     * @mbg.generated Mon Apr 30 14:26:05 CST 2018
     */
    int updateByExampleSelective(@Param("record") Problem record, @Param("example") ProblemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table problem
     *
     * @mbg.generated Mon Apr 30 14:26:05 CST 2018
     */
    int updateByExample(@Param("record") Problem record, @Param("example") ProblemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table problem
     *
     * @mbg.generated Mon Apr 30 14:26:05 CST 2018
     */
    int updateByPrimaryKeySelective(Problem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table problem
     *
     * @mbg.generated Mon Apr 30 14:26:05 CST 2018
     */
    int updateByPrimaryKey(Problem record);

    List<Problem> selectByExampleWithChapterID(Integer problemchapterid);
}