package com.hhips.dao.mapper.problem;

import com.hhips.dao.model.problem.SourceChapter;
import com.hhips.dao.model.problem.SourceChapterExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SourceChapterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sourcechapter
     *
     * @mbg.generated Fri May 11 21:27:43 CST 2018
     */
    long countByExample(SourceChapterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sourcechapter
     *
     * @mbg.generated Fri May 11 21:27:43 CST 2018
     */
    int deleteByExample(SourceChapterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sourcechapter
     *
     * @mbg.generated Fri May 11 21:27:43 CST 2018
     */
    int deleteByPrimaryKey(Integer idsourcechapter);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sourcechapter
     *
     * @mbg.generated Fri May 11 21:27:43 CST 2018
     */
    int insert(SourceChapter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sourcechapter
     *
     * @mbg.generated Fri May 11 21:27:43 CST 2018
     */
    int insertSelective(SourceChapter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sourcechapter
     *
     * @mbg.generated Fri May 11 21:27:43 CST 2018
     */
    List<SourceChapter> selectByExample(SourceChapterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sourcechapter
     *
     * @mbg.generated Fri May 11 21:27:43 CST 2018
     */
    SourceChapter selectByPrimaryKey(Integer idsourcechapter);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sourcechapter
     *
     * @mbg.generated Fri May 11 21:27:43 CST 2018
     */
    int updateByExampleSelective(@Param("record") SourceChapter record, @Param("example") SourceChapterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sourcechapter
     *
     * @mbg.generated Fri May 11 21:27:43 CST 2018
     */
    int updateByExample(@Param("record") SourceChapter record, @Param("example") SourceChapterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sourcechapter
     *
     * @mbg.generated Fri May 11 21:27:43 CST 2018
     */
    int updateByPrimaryKeySelective(SourceChapter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sourcechapter
     *
     * @mbg.generated Fri May 11 21:27:43 CST 2018
     */
    int updateByPrimaryKey(SourceChapter record);
}