package com.hhips.dao.mapper.problem;

import com.hhips.dao.model.problem.Source;
import com.hhips.dao.model.problem.SourceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table source
     *
     * @mbg.generated Fri May 11 21:27:43 CST 2018
     */
    long countByExample(SourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table source
     *
     * @mbg.generated Fri May 11 21:27:43 CST 2018
     */
    int deleteByExample(SourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table source
     *
     * @mbg.generated Fri May 11 21:27:43 CST 2018
     */
    int deleteByPrimaryKey(Integer idsource);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table source
     *
     * @mbg.generated Fri May 11 21:27:43 CST 2018
     */
    int insert(Source record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table source
     *
     * @mbg.generated Fri May 11 21:27:43 CST 2018
     */
    int insertSelective(Source record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table source
     *
     * @mbg.generated Fri May 11 21:27:43 CST 2018
     */
    List<Source> selectByExample(SourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table source
     *
     * @mbg.generated Fri May 11 21:27:43 CST 2018
     */
    Source selectByPrimaryKey(Integer idsource);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table source
     *
     * @mbg.generated Fri May 11 21:27:43 CST 2018
     */
    int updateByExampleSelective(@Param("record") Source record, @Param("example") SourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table source
     *
     * @mbg.generated Fri May 11 21:27:43 CST 2018
     */
    int updateByExample(@Param("record") Source record, @Param("example") SourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table source
     *
     * @mbg.generated Fri May 11 21:27:43 CST 2018
     */
    int updateByPrimaryKeySelective(Source record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table source
     *
     * @mbg.generated Fri May 11 21:27:43 CST 2018
     */
    int updateByPrimaryKey(Source record);
}