package com.hhips.dao.model.chapter;

import java.io.Serializable;

public class SysChapter implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_chapter.CHAPTER_ID
     *
     * @mbg.generated Mon Apr 30 14:05:33 CST 2018
     */
    /**
     * 菜单ID
     *
     * @mbg.generated Mon Apr 30 14:05:33 CST 2018
     */
    private String chapterId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_chapter.CHAPTER_PID
     *
     * @mbg.generated Mon Apr 30 14:05:33 CST 2018
     */
    /**
     * 菜单父ID
     *
     * @mbg.generated Mon Apr 30 14:05:33 CST 2018
     */
    private String chapterPid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_chapter.CHAPTER_NAME
     *
     * @mbg.generated Mon Apr 30 14:05:33 CST 2018
     */
    /**
     * 菜单名称
     *
     * @mbg.generated Mon Apr 30 14:05:33 CST 2018
     */
    private String chapterName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_chapter.CHAPTER_DESCRIBE
     *
     * @mbg.generated Mon Apr 30 14:05:33 CST 2018
     */
    /**
     * 菜单描述
     *
     * @mbg.generated Mon Apr 30 14:05:33 CST 2018
     */
    private String chapterDescribe;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_chapter.CHAPTER_URL
     *
     * @mbg.generated Mon Apr 30 14:05:33 CST 2018
     */
    /**
     * 菜单地址URL
     *
     * @mbg.generated Mon Apr 30 14:05:33 CST 2018
     */
    private String chapterUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_chapter.CHAPTER_ICON
     *
     * @mbg.generated Mon Apr 30 14:05:33 CST 2018
     */
    /**
     * 图标
     *
     * @mbg.generated Mon Apr 30 14:05:33 CST 2018
     */
    private String chapterIcon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_chapter.CHAPTER_INDEX
     *
     * @mbg.generated Mon Apr 30 14:05:33 CST 2018
     */
    /**
     * 菜单排序
     *
     * @mbg.generated Mon Apr 30 14:05:33 CST 2018
     */
    private Integer chapterIndex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_chapter.CHAPTER_TYPE
     *
     * @mbg.generated Mon Apr 30 14:05:33 CST 2018
     */
    /**
     * 菜单类型（文件夹/菜单）
     *
     * @mbg.generated Mon Apr 30 14:05:33 CST 2018
     */
    private String chapterType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_chapter.CHAPTER_LEVEL
     *
     * @mbg.generated Mon Apr 30 14:05:33 CST 2018
     */
    /**
     * 菜单级别
     *
     * @mbg.generated Mon Apr 30 14:05:33 CST 2018
     */
    private Integer chapterLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_chapter.CHAPTER_VALID
     *
     * @mbg.generated Mon Apr 30 14:05:33 CST 2018
     */
    /**
     * 有效值
     *
     * @mbg.generated Mon Apr 30 14:05:33 CST 2018
     */
    private Boolean chapterValid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_chapter.CHAPTER_SOURCEID
     *
     * @mbg.generated Mon Apr 30 14:05:33 CST 2018
     */
    /**
     * source表的idsource
     *
     * @mbg.generated Mon Apr 30 14:05:33 CST 2018
     */
    private Integer chapterSourceid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_chapter.CHAPTER_CHAPTERID
     *
     * @mbg.generated Mon Apr 30 14:05:33 CST 2018
     */
    /**
     * sourcechapter表的idsourcechapter
     *
     * @mbg.generated Mon Apr 30 14:05:33 CST 2018
     */
    private Integer chapterChapterid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_chapter
     *
     * @mbg.generated Mon Apr 30 14:05:33 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_chapter.CHAPTER_ID
     *
     * @return the value of sys_chapter.CHAPTER_ID
     *
     * @mbg.generated Mon Apr 30 14:05:33 CST 2018
     */
    public String getChapterId() {
        return chapterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_chapter.CHAPTER_ID
     *
     * @param chapterId the value for sys_chapter.CHAPTER_ID
     *
     * @mbg.generated Mon Apr 30 14:05:33 CST 2018
     */
    public void setChapterId(String chapterId) {
        this.chapterId = chapterId == null ? null : chapterId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_chapter.CHAPTER_PID
     *
     * @return the value of sys_chapter.CHAPTER_PID
     *
     * @mbg.generated Mon Apr 30 14:05:33 CST 2018
     */
    public String getChapterPid() {
        return chapterPid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_chapter.CHAPTER_PID
     *
     * @param chapterPid the value for sys_chapter.CHAPTER_PID
     *
     * @mbg.generated Mon Apr 30 14:05:33 CST 2018
     */
    public void setChapterPid(String chapterPid) {
        this.chapterPid = chapterPid == null ? null : chapterPid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_chapter.CHAPTER_NAME
     *
     * @return the value of sys_chapter.CHAPTER_NAME
     *
     * @mbg.generated Mon Apr 30 14:05:33 CST 2018
     */
    public String getChapterName() {
        return chapterName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_chapter.CHAPTER_NAME
     *
     * @param chapterName the value for sys_chapter.CHAPTER_NAME
     *
     * @mbg.generated Mon Apr 30 14:05:33 CST 2018
     */
    public void setChapterName(String chapterName) {
        this.chapterName = chapterName == null ? null : chapterName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_chapter.CHAPTER_DESCRIBE
     *
     * @return the value of sys_chapter.CHAPTER_DESCRIBE
     *
     * @mbg.generated Mon Apr 30 14:05:33 CST 2018
     */
    public String getChapterDescribe() {
        return chapterDescribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_chapter.CHAPTER_DESCRIBE
     *
     * @param chapterDescribe the value for sys_chapter.CHAPTER_DESCRIBE
     *
     * @mbg.generated Mon Apr 30 14:05:33 CST 2018
     */
    public void setChapterDescribe(String chapterDescribe) {
        this.chapterDescribe = chapterDescribe == null ? null : chapterDescribe.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_chapter.CHAPTER_URL
     *
     * @return the value of sys_chapter.CHAPTER_URL
     *
     * @mbg.generated Mon Apr 30 14:05:33 CST 2018
     */
    public String getChapterUrl() {
        return chapterUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_chapter.CHAPTER_URL
     *
     * @param chapterUrl the value for sys_chapter.CHAPTER_URL
     *
     * @mbg.generated Mon Apr 30 14:05:33 CST 2018
     */
    public void setChapterUrl(String chapterUrl) {
        this.chapterUrl = chapterUrl == null ? null : chapterUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_chapter.CHAPTER_ICON
     *
     * @return the value of sys_chapter.CHAPTER_ICON
     *
     * @mbg.generated Mon Apr 30 14:05:33 CST 2018
     */
    public String getChapterIcon() {
        return chapterIcon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_chapter.CHAPTER_ICON
     *
     * @param chapterIcon the value for sys_chapter.CHAPTER_ICON
     *
     * @mbg.generated Mon Apr 30 14:05:33 CST 2018
     */
    public void setChapterIcon(String chapterIcon) {
        this.chapterIcon = chapterIcon == null ? null : chapterIcon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_chapter.CHAPTER_INDEX
     *
     * @return the value of sys_chapter.CHAPTER_INDEX
     *
     * @mbg.generated Mon Apr 30 14:05:33 CST 2018
     */
    public Integer getChapterIndex() {
        return chapterIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_chapter.CHAPTER_INDEX
     *
     * @param chapterIndex the value for sys_chapter.CHAPTER_INDEX
     *
     * @mbg.generated Mon Apr 30 14:05:33 CST 2018
     */
    public void setChapterIndex(Integer chapterIndex) {
        this.chapterIndex = chapterIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_chapter.CHAPTER_TYPE
     *
     * @return the value of sys_chapter.CHAPTER_TYPE
     *
     * @mbg.generated Mon Apr 30 14:05:33 CST 2018
     */
    public String getChapterType() {
        return chapterType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_chapter.CHAPTER_TYPE
     *
     * @param chapterType the value for sys_chapter.CHAPTER_TYPE
     *
     * @mbg.generated Mon Apr 30 14:05:33 CST 2018
     */
    public void setChapterType(String chapterType) {
        this.chapterType = chapterType == null ? null : chapterType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_chapter.CHAPTER_LEVEL
     *
     * @return the value of sys_chapter.CHAPTER_LEVEL
     *
     * @mbg.generated Mon Apr 30 14:05:33 CST 2018
     */
    public Integer getChapterLevel() {
        return chapterLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_chapter.CHAPTER_LEVEL
     *
     * @param chapterLevel the value for sys_chapter.CHAPTER_LEVEL
     *
     * @mbg.generated Mon Apr 30 14:05:33 CST 2018
     */
    public void setChapterLevel(Integer chapterLevel) {
        this.chapterLevel = chapterLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_chapter.CHAPTER_VALID
     *
     * @return the value of sys_chapter.CHAPTER_VALID
     *
     * @mbg.generated Mon Apr 30 14:05:33 CST 2018
     */
    public Boolean getChapterValid() {
        return chapterValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_chapter.CHAPTER_VALID
     *
     * @param chapterValid the value for sys_chapter.CHAPTER_VALID
     *
     * @mbg.generated Mon Apr 30 14:05:33 CST 2018
     */
    public void setChapterValid(Boolean chapterValid) {
        this.chapterValid = chapterValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_chapter.CHAPTER_SOURCEID
     *
     * @return the value of sys_chapter.CHAPTER_SOURCEID
     *
     * @mbg.generated Mon Apr 30 14:05:33 CST 2018
     */
    public Integer getChapterSourceid() {
        return chapterSourceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_chapter.CHAPTER_SOURCEID
     *
     * @param chapterSourceid the value for sys_chapter.CHAPTER_SOURCEID
     *
     * @mbg.generated Mon Apr 30 14:05:33 CST 2018
     */
    public void setChapterSourceid(Integer chapterSourceid) {
        this.chapterSourceid = chapterSourceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_chapter.CHAPTER_CHAPTERID
     *
     * @return the value of sys_chapter.CHAPTER_CHAPTERID
     *
     * @mbg.generated Mon Apr 30 14:05:33 CST 2018
     */
    public Integer getChapterChapterid() {
        return chapterChapterid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_chapter.CHAPTER_CHAPTERID
     *
     * @param chapterChapterid the value for sys_chapter.CHAPTER_CHAPTERID
     *
     * @mbg.generated Mon Apr 30 14:05:33 CST 2018
     */
    public void setChapterChapterid(Integer chapterChapterid) {
        this.chapterChapterid = chapterChapterid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_chapter
     *
     * @mbg.generated Mon Apr 30 14:05:33 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", chapterId=").append(chapterId);
        sb.append(", chapterPid=").append(chapterPid);
        sb.append(", chapterName=").append(chapterName);
        sb.append(", chapterDescribe=").append(chapterDescribe);
        sb.append(", chapterUrl=").append(chapterUrl);
        sb.append(", chapterIcon=").append(chapterIcon);
        sb.append(", chapterIndex=").append(chapterIndex);
        sb.append(", chapterType=").append(chapterType);
        sb.append(", chapterLevel=").append(chapterLevel);
        sb.append(", chapterValid=").append(chapterValid);
        sb.append(", chapterSourceid=").append(chapterSourceid);
        sb.append(", chapterChapterid=").append(chapterChapterid);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}