package com.hhips.dao.model.problem;

import java.io.Serializable;

public class Module implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module.idmodule
     *
     * @mbg.generated Fri May 11 21:27:43 CST 2018
     */
    private Integer idmodule;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module.modulename
     *
     * @mbg.generated Fri May 11 21:27:43 CST 2018
     */
    private String modulename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table module
     *
     * @mbg.generated Fri May 11 21:27:43 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column module.idmodule
     *
     * @return the value of module.idmodule
     *
     * @mbg.generated Fri May 11 21:27:43 CST 2018
     */
    public Integer getIdmodule() {
        return idmodule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column module.idmodule
     *
     * @param idmodule the value for module.idmodule
     *
     * @mbg.generated Fri May 11 21:27:43 CST 2018
     */
    public void setIdmodule(Integer idmodule) {
        this.idmodule = idmodule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column module.modulename
     *
     * @return the value of module.modulename
     *
     * @mbg.generated Fri May 11 21:27:43 CST 2018
     */
    public String getModulename() {
        return modulename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column module.modulename
     *
     * @param modulename the value for module.modulename
     *
     * @mbg.generated Fri May 11 21:27:43 CST 2018
     */
    public void setModulename(String modulename) {
        this.modulename = modulename == null ? null : modulename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table module
     *
     * @mbg.generated Fri May 11 21:27:43 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", idmodule=").append(idmodule);
        sb.append(", modulename=").append(modulename);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}