package com.hhips.dao.model.problem;

import java.io.Serializable;

public class Paperproblem implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paperproblem.paperproblemid
     *
     * @mbg.generated Thu May 31 15:35:41 CST 2018
     */
    private Integer paperproblemid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paperproblem.paperid
     *
     * @mbg.generated Thu May 31 15:35:41 CST 2018
     */
    private Integer paperid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paperproblem.problemid
     *
     * @mbg.generated Thu May 31 15:35:41 CST 2018
     */
    private Integer problemid;

    private Integer problemlevel;

    private String problemdetail;

    private Integer problemchapterid;

    private String problemindex;

    private Integer problemmodule;

    private Integer problemcisactive;

    private String problemanswerstring;

    private String problemanswerdetail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table paperproblem
     *
     * @mbg.generated Thu May 31 15:35:41 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paperproblem.paperproblemid
     *
     * @return the value of paperproblem.paperproblemid
     *
     * @mbg.generated Thu May 31 15:35:41 CST 2018
     */
    public Integer getPaperproblemid() {
        return paperproblemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paperproblem.paperproblemid
     *
     * @param paperproblemid the value for paperproblem.paperproblemid
     *
     * @mbg.generated Thu May 31 15:35:41 CST 2018
     */
    public void setPaperproblemid(Integer paperproblemid) {
        this.paperproblemid = paperproblemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paperproblem.paperid
     *
     * @return the value of paperproblem.paperid
     *
     * @mbg.generated Thu May 31 15:35:41 CST 2018
     */
    public Integer getPaperid() {
        return paperid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paperproblem.paperid
     *
     * @param paperid the value for paperproblem.paperid
     *
     * @mbg.generated Thu May 31 15:35:41 CST 2018
     */
    public void setPaperid(Integer paperid) {
        this.paperid = paperid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paperproblem.problemid
     *
     * @return the value of paperproblem.problemid
     *
     * @mbg.generated Thu May 31 15:35:41 CST 2018
     */
    public Integer getProblemid() {
        return problemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paperproblem.problemid
     *
     * @param problemid the value for paperproblem.problemid
     *
     * @mbg.generated Thu May 31 15:35:41 CST 2018
     */
    public void setProblemid(Integer problemid) {
        this.problemid = problemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column problem.problemlevel
     *
     * @return the value of problem.problemlevel
     *
     * @mbg.generated Mon Apr 30 14:26:05 CST 2018
     */
    public Integer getProblemlevel() {
        return problemlevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column problem.problemlevel
     *
     * @param problemlevel the value for problem.problemlevel
     *
     * @mbg.generated Mon Apr 30 14:26:05 CST 2018
     */
    public void setProblemlevel(Integer problemlevel) {
        this.problemlevel = problemlevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column problem.problemdetail
     *
     * @return the value of problem.problemdetail
     *
     * @mbg.generated Mon Apr 30 14:26:05 CST 2018
     */
    public String getProblemdetail() {
        return problemdetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column problem.problemdetail
     *
     * @param problemdetail the value for problem.problemdetail
     *
     * @mbg.generated Mon Apr 30 14:26:05 CST 2018
     */
    public void setProblemdetail(String problemdetail) {
        this.problemdetail = problemdetail == null ? null : problemdetail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column problem.problemchapterid
     *
     * @return the value of problem.problemchapterid
     *
     * @mbg.generated Mon Apr 30 14:26:05 CST 2018
     */
    public Integer getProblemchapterid() {
        return problemchapterid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column problem.problemchapterid
     *
     * @param problemchapterid the value for problem.problemchapterid
     *
     * @mbg.generated Mon Apr 30 14:26:05 CST 2018
     */
    public void setProblemchapterid(Integer problemchapterid) {
        this.problemchapterid = problemchapterid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column problem.problemindex
     *
     * @return the value of problem.problemindex
     *
     * @mbg.generated Mon Apr 30 14:26:05 CST 2018
     */
    public String getProblemindex() {
        return problemindex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column problem.problemindex
     *
     * @param problemindex the value for problem.problemindex
     *
     * @mbg.generated Mon Apr 30 14:26:05 CST 2018
     */
    public void setProblemindex(String problemindex) {
        this.problemindex = problemindex == null ? null : problemindex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column problem.problemmodule
     *
     * @return the value of problem.problemmodule
     *
     * @mbg.generated Mon Apr 30 14:26:05 CST 2018
     */
    public Integer getProblemmodule() {
        return problemmodule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column problem.problemmodule
     *
     * @param problemmodule the value for problem.problemmodule
     *
     * @mbg.generated Mon Apr 30 14:26:05 CST 2018
     */
    public void setProblemmodule(Integer problemmodule) {
        this.problemmodule = problemmodule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column problem.problemcisactive
     *
     * @return the value of problem.problemcisactive
     *
     * @mbg.generated Mon Apr 30 14:26:05 CST 2018
     */
    public Integer getProblemcisactive() {
        return problemcisactive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column problem.problemcisactive
     *
     * @param problemcisactive the value for problem.problemcisactive
     *
     * @mbg.generated Mon Apr 30 14:26:05 CST 2018
     */
    public void setProblemcisactive(Integer problemcisactive) {
        this.problemcisactive = problemcisactive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column problem.problemanswerstring
     *
     * @return the value of problem.problemanswerstring
     *
     * @mbg.generated Mon Apr 30 14:26:05 CST 2018
     */
    public String getProblemanswerstring() {
        return problemanswerstring;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column problem.problemanswerstring
     *
     * @param problemanswerstring the value for problem.problemanswerstring
     *
     * @mbg.generated Mon Apr 30 14:26:05 CST 2018
     */
    public void setProblemanswerstring(String problemanswerstring) {
        this.problemanswerstring = problemanswerstring == null ? null : problemanswerstring.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column problem.problemanswerdetail
     *
     * @return the value of problem.problemanswerdetail
     *
     * @mbg.generated Mon Apr 30 14:26:05 CST 2018
     */
    public String getProblemanswerdetail() {
        return problemanswerdetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column problem.problemanswerdetail
     *
     * @param problemanswerdetail the value for problem.problemanswerdetail
     *
     * @mbg.generated Mon Apr 30 14:26:05 CST 2018
     */
    public void setProblemanswerdetail(String problemanswerdetail) {
        this.problemanswerdetail = problemanswerdetail == null ? null : problemanswerdetail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paperproblem
     *
     * @mbg.generated Thu May 31 15:35:41 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", paperproblemid=").append(paperproblemid);
        sb.append(", paperid=").append(paperid);
        sb.append(", problemid=").append(problemid);
        sb.append(", problemlevel=").append(problemlevel);
        sb.append(", problemdetail=").append(problemdetail);
        sb.append(", problemchapterid=").append(problemchapterid);
        sb.append(", problemindex=").append(problemindex);
        sb.append(", problemmodule=").append(problemmodule);
        sb.append(", problemcisactive=").append(problemcisactive);
        sb.append(", problemanswerstring=").append(problemanswerstring);
        sb.append(", problemanswerdetail=").append(problemanswerdetail);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}