package com.hhips.dao.model.problem;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

public class PaperproblemExample implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table paperproblem
     *
     * @mbg.generated Thu May 31 15:35:41 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table paperproblem
     *
     * @mbg.generated Thu May 31 15:35:41 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table paperproblem
     *
     * @mbg.generated Thu May 31 15:35:41 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table paperproblem
     *
     * @mbg.generated Thu May 31 15:35:41 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paperproblem
     *
     * @mbg.generated Thu May 31 15:35:41 CST 2018
     */
    public PaperproblemExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paperproblem
     *
     * @mbg.generated Thu May 31 15:35:41 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paperproblem
     *
     * @mbg.generated Thu May 31 15:35:41 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paperproblem
     *
     * @mbg.generated Thu May 31 15:35:41 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paperproblem
     *
     * @mbg.generated Thu May 31 15:35:41 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paperproblem
     *
     * @mbg.generated Thu May 31 15:35:41 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paperproblem
     *
     * @mbg.generated Thu May 31 15:35:41 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paperproblem
     *
     * @mbg.generated Thu May 31 15:35:41 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paperproblem
     *
     * @mbg.generated Thu May 31 15:35:41 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paperproblem
     *
     * @mbg.generated Thu May 31 15:35:41 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paperproblem
     *
     * @mbg.generated Thu May 31 15:35:41 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table paperproblem
     *
     * @mbg.generated Thu May 31 15:35:41 CST 2018
     */
    protected abstract static class GeneratedCriteria implements Serializable {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPaperproblemidIsNull() {
            addCriterion("paperproblemid is null");
            return (Criteria) this;
        }

        public Criteria andPaperproblemidIsNotNull() {
            addCriterion("paperproblemid is not null");
            return (Criteria) this;
        }

        public Criteria andPaperproblemidEqualTo(Integer value) {
            addCriterion("paperproblemid =", value, "paperproblemid");
            return (Criteria) this;
        }

        public Criteria andPaperproblemidNotEqualTo(Integer value) {
            addCriterion("paperproblemid <>", value, "paperproblemid");
            return (Criteria) this;
        }

        public Criteria andPaperproblemidGreaterThan(Integer value) {
            addCriterion("paperproblemid >", value, "paperproblemid");
            return (Criteria) this;
        }

        public Criteria andPaperproblemidGreaterThanOrEqualTo(Integer value) {
            addCriterion("paperproblemid >=", value, "paperproblemid");
            return (Criteria) this;
        }

        public Criteria andPaperproblemidLessThan(Integer value) {
            addCriterion("paperproblemid <", value, "paperproblemid");
            return (Criteria) this;
        }

        public Criteria andPaperproblemidLessThanOrEqualTo(Integer value) {
            addCriterion("paperproblemid <=", value, "paperproblemid");
            return (Criteria) this;
        }

        public Criteria andPaperproblemidIn(List<Integer> values) {
            addCriterion("paperproblemid in", values, "paperproblemid");
            return (Criteria) this;
        }

        public Criteria andPaperproblemidNotIn(List<Integer> values) {
            addCriterion("paperproblemid not in", values, "paperproblemid");
            return (Criteria) this;
        }

        public Criteria andPaperproblemidBetween(Integer value1, Integer value2) {
            addCriterion("paperproblemid between", value1, value2, "paperproblemid");
            return (Criteria) this;
        }

        public Criteria andPaperproblemidNotBetween(Integer value1, Integer value2) {
            addCriterion("paperproblemid not between", value1, value2, "paperproblemid");
            return (Criteria) this;
        }

        public Criteria andPaperidIsNull() {
            addCriterion("paperid is null");
            return (Criteria) this;
        }

        public Criteria andPaperidIsNotNull() {
            addCriterion("paperid is not null");
            return (Criteria) this;
        }

        public Criteria andPaperidEqualTo(Integer value) {
            addCriterion("paperid =", value, "paperid");
            return (Criteria) this;
        }

        public Criteria andPaperidNotEqualTo(Integer value) {
            addCriterion("paperid <>", value, "paperid");
            return (Criteria) this;
        }

        public Criteria andPaperidGreaterThan(Integer value) {
            addCriterion("paperid >", value, "paperid");
            return (Criteria) this;
        }

        public Criteria andPaperidGreaterThanOrEqualTo(Integer value) {
            addCriterion("paperid >=", value, "paperid");
            return (Criteria) this;
        }

        public Criteria andPaperidLessThan(Integer value) {
            addCriterion("paperid <", value, "paperid");
            return (Criteria) this;
        }

        public Criteria andPaperidLessThanOrEqualTo(Integer value) {
            addCriterion("paperid <=", value, "paperid");
            return (Criteria) this;
        }

        public Criteria andPaperidIn(List<Integer> values) {
            addCriterion("paperid in", values, "paperid");
            return (Criteria) this;
        }

        public Criteria andPaperidNotIn(List<Integer> values) {
            addCriterion("paperid not in", values, "paperid");
            return (Criteria) this;
        }

        public Criteria andPaperidBetween(Integer value1, Integer value2) {
            addCriterion("paperid between", value1, value2, "paperid");
            return (Criteria) this;
        }

        public Criteria andPaperidNotBetween(Integer value1, Integer value2) {
            addCriterion("paperid not between", value1, value2, "paperid");
            return (Criteria) this;
        }

        public Criteria andProblemidIsNull() {
            addCriterion("problemid is null");
            return (Criteria) this;
        }

        public Criteria andProblemidIsNotNull() {
            addCriterion("problemid is not null");
            return (Criteria) this;
        }

        public Criteria andProblemidEqualTo(Integer value) {
            addCriterion("problemid =", value, "problemid");
            return (Criteria) this;
        }

        public Criteria andProblemidNotEqualTo(Integer value) {
            addCriterion("problemid <>", value, "problemid");
            return (Criteria) this;
        }

        public Criteria andProblemidGreaterThan(Integer value) {
            addCriterion("problemid >", value, "problemid");
            return (Criteria) this;
        }

        public Criteria andProblemidGreaterThanOrEqualTo(Integer value) {
            addCriterion("problemid >=", value, "problemid");
            return (Criteria) this;
        }

        public Criteria andProblemidLessThan(Integer value) {
            addCriterion("problemid <", value, "problemid");
            return (Criteria) this;
        }

        public Criteria andProblemidLessThanOrEqualTo(Integer value) {
            addCriterion("problemid <=", value, "problemid");
            return (Criteria) this;
        }

        public Criteria andProblemidIn(List<Integer> values) {
            addCriterion("problemid in", values, "problemid");
            return (Criteria) this;
        }

        public Criteria andProblemidNotIn(List<Integer> values) {
            addCriterion("problemid not in", values, "problemid");
            return (Criteria) this;
        }

        public Criteria andProblemidBetween(Integer value1, Integer value2) {
            addCriterion("problemid between", value1, value2, "problemid");
            return (Criteria) this;
        }

        public Criteria andProblemidNotBetween(Integer value1, Integer value2) {
            addCriterion("problemid not between", value1, value2, "problemid");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table paperproblem
     *
     * @mbg.generated do_not_delete_during_merge Thu May 31 15:35:41 CST 2018
     */
    public static class Criteria extends GeneratedCriteria implements Serializable {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table paperproblem
     *
     * @mbg.generated Thu May 31 15:35:41 CST 2018
     */
    public static class Criterion implements Serializable {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}