package com.hhips.dao.model.problem;

import java.io.Serializable;
import java.util.Date;

public class Paper implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper.idpaper
     *
     * @mbg.generated Thu May 31 15:35:41 CST 2018
     */
    private Integer idpaper;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper.papername
     *
     * @mbg.generated Thu May 31 15:35:41 CST 2018
     */
    private String papername;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper.paperdate
     *
     * @mbg.generated Thu May 31 15:35:41 CST 2018
     */
    private Date paperdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper.isactive
     *
     * @mbg.generated Thu May 31 15:35:41 CST 2018
     */
    private Integer isactive;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table paper
     *
     * @mbg.generated Thu May 31 15:35:41 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper.idpaper
     *
     * @return the value of paper.idpaper
     *
     * @mbg.generated Thu May 31 15:35:41 CST 2018
     */
    public Integer getIdpaper() {
        return idpaper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper.idpaper
     *
     * @param idpaper the value for paper.idpaper
     *
     * @mbg.generated Thu May 31 15:35:41 CST 2018
     */
    public void setIdpaper(Integer idpaper) {
        this.idpaper = idpaper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper.papername
     *
     * @return the value of paper.papername
     *
     * @mbg.generated Thu May 31 15:35:41 CST 2018
     */
    public String getPapername() {
        return papername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper.papername
     *
     * @param papername the value for paper.papername
     *
     * @mbg.generated Thu May 31 15:35:41 CST 2018
     */
    public void setPapername(String papername) {
        this.papername = papername == null ? null : papername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper.paperdate
     *
     * @return the value of paper.paperdate
     *
     * @mbg.generated Thu May 31 15:35:41 CST 2018
     */
    public Date getPaperdate() {
        return paperdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper.paperdate
     *
     * @param paperdate the value for paper.paperdate
     *
     * @mbg.generated Thu May 31 15:35:41 CST 2018
     */
    public void setPaperdate(Date paperdate) {
        this.paperdate = paperdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper.isactive
     *
     * @return the value of paper.isactive
     *
     * @mbg.generated Thu May 31 15:35:41 CST 2018
     */
    public Integer getIsactive() {
        return isactive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper.isactive
     *
     * @param isactive the value for paper.isactive
     *
     * @mbg.generated Thu May 31 15:35:41 CST 2018
     */
    public void setIsactive(Integer isactive) {
        this.isactive = isactive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper
     *
     * @mbg.generated Thu May 31 15:35:41 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", idpaper=").append(idpaper);
        sb.append(", papername=").append(papername);
        sb.append(", paperdate=").append(paperdate);
        sb.append(", isactive=").append(isactive);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}