package com.hhips.dao.model.problem;

import java.io.Serializable;
import java.util.List;

public class Problem implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column problem.idproblem
     *
     * @mbg.generated Mon Apr 30 14:26:05 CST 2018
     */
    private Integer idproblem;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column problem.problemlevel
     *
     * @mbg.generated Mon Apr 30 14:26:05 CST 2018
     */
    private Integer problemlevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column problem.problemdetail
     *
     * @mbg.generated Mon Apr 30 14:26:05 CST 2018
     */
    private String problemdetail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column problem.problemchapterid
     *
     * @mbg.generated Mon Apr 30 14:26:05 CST 2018
     */
    private Integer problemchapterid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column problem.problemindex
     *
     * @mbg.generated Mon Apr 30 14:26:05 CST 2018
     */
    private String problemindex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column problem.problemmodule
     *
     * @mbg.generated Mon Apr 30 14:26:05 CST 2018
     */
    private Integer problemmodule;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column problem.problemcisactive
     *
     * @mbg.generated Mon Apr 30 14:26:05 CST 2018
     */
    private Integer problemcisactive;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column problem.problemanswerstring
     *
     * @mbg.generated Mon Apr 30 14:26:05 CST 2018
     */
    private String problemanswerstring;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column problem.problemanswerdetail
     *
     * @mbg.generated Mon Apr 30 14:26:05 CST 2018
     */
    private String problemanswerdetail;

    private List<Work> works;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table problem
     *
     * @mbg.generated Mon Apr 30 14:26:05 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column problem.idproblem
     *
     * @return the value of problem.idproblem
     *
     * @mbg.generated Mon Apr 30 14:26:05 CST 2018
     */
    public Integer getIdproblem() {
        return idproblem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column problem.idproblem
     *
     * @param idproblem the value for problem.idproblem
     *
     * @mbg.generated Mon Apr 30 14:26:05 CST 2018
     */
    public void setIdproblem(Integer idproblem) {
        this.idproblem = idproblem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column problem.problemlevel
     *
     * @return the value of problem.problemlevel
     *
     * @mbg.generated Mon Apr 30 14:26:05 CST 2018
     */
    public Integer getProblemlevel() {
        return problemlevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column problem.problemlevel
     *
     * @param problemlevel the value for problem.problemlevel
     *
     * @mbg.generated Mon Apr 30 14:26:05 CST 2018
     */
    public void setProblemlevel(Integer problemlevel) {
        this.problemlevel = problemlevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column problem.problemdetail
     *
     * @return the value of problem.problemdetail
     *
     * @mbg.generated Mon Apr 30 14:26:05 CST 2018
     */
    public String getProblemdetail() {
        return problemdetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column problem.problemdetail
     *
     * @param problemdetail the value for problem.problemdetail
     *
     * @mbg.generated Mon Apr 30 14:26:05 CST 2018
     */
    public void setProblemdetail(String problemdetail) {
        this.problemdetail = problemdetail == null ? null : problemdetail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column problem.problemchapterid
     *
     * @return the value of problem.problemchapterid
     *
     * @mbg.generated Mon Apr 30 14:26:05 CST 2018
     */
    public Integer getProblemchapterid() {
        return problemchapterid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column problem.problemchapterid
     *
     * @param problemchapterid the value for problem.problemchapterid
     *
     * @mbg.generated Mon Apr 30 14:26:05 CST 2018
     */
    public void setProblemchapterid(Integer problemchapterid) {
        this.problemchapterid = problemchapterid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column problem.problemindex
     *
     * @return the value of problem.problemindex
     *
     * @mbg.generated Mon Apr 30 14:26:05 CST 2018
     */
    public String getProblemindex() {
        return problemindex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column problem.problemindex
     *
     * @param problemindex the value for problem.problemindex
     *
     * @mbg.generated Mon Apr 30 14:26:05 CST 2018
     */
    public void setProblemindex(String problemindex) {
        this.problemindex = problemindex == null ? null : problemindex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column problem.problemmodule
     *
     * @return the value of problem.problemmodule
     *
     * @mbg.generated Mon Apr 30 14:26:05 CST 2018
     */
    public Integer getProblemmodule() {
        return problemmodule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column problem.problemmodule
     *
     * @param problemmodule the value for problem.problemmodule
     *
     * @mbg.generated Mon Apr 30 14:26:05 CST 2018
     */
    public void setProblemmodule(Integer problemmodule) {
        this.problemmodule = problemmodule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column problem.problemcisactive
     *
     * @return the value of problem.problemcisactive
     *
     * @mbg.generated Mon Apr 30 14:26:05 CST 2018
     */
    public Integer getProblemcisactive() {
        return problemcisactive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column problem.problemcisactive
     *
     * @param problemcisactive the value for problem.problemcisactive
     *
     * @mbg.generated Mon Apr 30 14:26:05 CST 2018
     */
    public void setProblemcisactive(Integer problemcisactive) {
        this.problemcisactive = problemcisactive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column problem.problemanswerstring
     *
     * @return the value of problem.problemanswerstring
     *
     * @mbg.generated Mon Apr 30 14:26:05 CST 2018
     */
    public String getProblemanswerstring() {
        return problemanswerstring;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column problem.problemanswerstring
     *
     * @param problemanswerstring the value for problem.problemanswerstring
     *
     * @mbg.generated Mon Apr 30 14:26:05 CST 2018
     */
    public void setProblemanswerstring(String problemanswerstring) {
        this.problemanswerstring = problemanswerstring == null ? null : problemanswerstring.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column problem.problemanswerdetail
     *
     * @return the value of problem.problemanswerdetail
     *
     * @mbg.generated Mon Apr 30 14:26:05 CST 2018
     */
    public String getProblemanswerdetail() {
        return problemanswerdetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column problem.problemanswerdetail
     *
     * @param problemanswerdetail the value for problem.problemanswerdetail
     *
     * @mbg.generated Mon Apr 30 14:26:05 CST 2018
     */
    public void setProblemanswerdetail(String problemanswerdetail) {
        this.problemanswerdetail = problemanswerdetail == null ? null : problemanswerdetail.trim();
    }

    public List<Work> getWorks() {
        return works;
    }

    public void setWorks(List<Work> works) {
        this.works = works;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table problem
     *
     * @mbg.generated Mon Apr 30 14:26:05 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", idproblem=").append(idproblem);
        sb.append(", problemlevel=").append(problemlevel);
        sb.append(", problemdetail=").append(problemdetail);
        sb.append(", problemchapterid=").append(problemchapterid);
        sb.append(", problemindex=").append(problemindex);
        sb.append(", problemmodule=").append(problemmodule);
        sb.append(", problemcisactive=").append(problemcisactive);
        sb.append(", problemanswerstring=").append(problemanswerstring);
        sb.append(", problemanswerdetail=").append(problemanswerdetail);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}