package com.hhips.dao.model.problem;

import java.io.Serializable;

public class SourceChapter implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sourcechapter.idsourcechapter
     *
     * @mbg.generated Fri May 11 21:27:43 CST 2018
     */
    private Integer idsourcechapter;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sourcechapter.sourcechaptername
     *
     * @mbg.generated Fri May 11 21:27:43 CST 2018
     */
    private String sourcechaptername;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sourcechapter.sourcechapterindex
     *
     * @mbg.generated Fri May 11 21:27:43 CST 2018
     */
    private Integer sourcechapterindex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sourcechapter.sourceid
     *
     * @mbg.generated Fri May 11 21:27:43 CST 2018
     */
    private Integer sourceid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sourcechapter
     *
     * @mbg.generated Fri May 11 21:27:43 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sourcechapter.idsourcechapter
     *
     * @return the value of sourcechapter.idsourcechapter
     *
     * @mbg.generated Fri May 11 21:27:43 CST 2018
     */
    public Integer getIdsourcechapter() {
        return idsourcechapter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sourcechapter.idsourcechapter
     *
     * @param idsourcechapter the value for sourcechapter.idsourcechapter
     *
     * @mbg.generated Fri May 11 21:27:43 CST 2018
     */
    public void setIdsourcechapter(Integer idsourcechapter) {
        this.idsourcechapter = idsourcechapter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sourcechapter.sourcechaptername
     *
     * @return the value of sourcechapter.sourcechaptername
     *
     * @mbg.generated Fri May 11 21:27:43 CST 2018
     */
    public String getSourcechaptername() {
        return sourcechaptername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sourcechapter.sourcechaptername
     *
     * @param sourcechaptername the value for sourcechapter.sourcechaptername
     *
     * @mbg.generated Fri May 11 21:27:43 CST 2018
     */
    public void setSourcechaptername(String sourcechaptername) {
        this.sourcechaptername = sourcechaptername == null ? null : sourcechaptername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sourcechapter.sourcechapterindex
     *
     * @return the value of sourcechapter.sourcechapterindex
     *
     * @mbg.generated Fri May 11 21:27:43 CST 2018
     */
    public Integer getSourcechapterindex() {
        return sourcechapterindex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sourcechapter.sourcechapterindex
     *
     * @param sourcechapterindex the value for sourcechapter.sourcechapterindex
     *
     * @mbg.generated Fri May 11 21:27:43 CST 2018
     */
    public void setSourcechapterindex(Integer sourcechapterindex) {
        this.sourcechapterindex = sourcechapterindex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sourcechapter.sourceid
     *
     * @return the value of sourcechapter.sourceid
     *
     * @mbg.generated Fri May 11 21:27:43 CST 2018
     */
    public Integer getSourceid() {
        return sourceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sourcechapter.sourceid
     *
     * @param sourceid the value for sourcechapter.sourceid
     *
     * @mbg.generated Fri May 11 21:27:43 CST 2018
     */
    public void setSourceid(Integer sourceid) {
        this.sourceid = sourceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sourcechapter
     *
     * @mbg.generated Fri May 11 21:27:43 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", idsourcechapter=").append(idsourcechapter);
        sb.append(", sourcechaptername=").append(sourcechaptername);
        sb.append(", sourcechapterindex=").append(sourcechapterindex);
        sb.append(", sourceid=").append(sourceid);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}