package com.hhips.dao.model.problem;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

public class SourceChapterExample implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sourcechapter
     *
     * @mbg.generated Fri May 11 21:27:43 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sourcechapter
     *
     * @mbg.generated Fri May 11 21:27:43 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sourcechapter
     *
     * @mbg.generated Fri May 11 21:27:43 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sourcechapter
     *
     * @mbg.generated Fri May 11 21:27:43 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sourcechapter
     *
     * @mbg.generated Fri May 11 21:27:43 CST 2018
     */
    public SourceChapterExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sourcechapter
     *
     * @mbg.generated Fri May 11 21:27:43 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sourcechapter
     *
     * @mbg.generated Fri May 11 21:27:43 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sourcechapter
     *
     * @mbg.generated Fri May 11 21:27:43 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sourcechapter
     *
     * @mbg.generated Fri May 11 21:27:43 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sourcechapter
     *
     * @mbg.generated Fri May 11 21:27:43 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sourcechapter
     *
     * @mbg.generated Fri May 11 21:27:43 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sourcechapter
     *
     * @mbg.generated Fri May 11 21:27:43 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sourcechapter
     *
     * @mbg.generated Fri May 11 21:27:43 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sourcechapter
     *
     * @mbg.generated Fri May 11 21:27:43 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sourcechapter
     *
     * @mbg.generated Fri May 11 21:27:43 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sourcechapter
     *
     * @mbg.generated Fri May 11 21:27:43 CST 2018
     */
    protected abstract static class GeneratedCriteria implements Serializable {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdsourcechapterIsNull() {
            addCriterion("idsourcechapter is null");
            return (Criteria) this;
        }

        public Criteria andIdsourcechapterIsNotNull() {
            addCriterion("idsourcechapter is not null");
            return (Criteria) this;
        }

        public Criteria andIdsourcechapterEqualTo(Integer value) {
            addCriterion("idsourcechapter =", value, "idsourcechapter");
            return (Criteria) this;
        }

        public Criteria andIdsourcechapterNotEqualTo(Integer value) {
            addCriterion("idsourcechapter <>", value, "idsourcechapter");
            return (Criteria) this;
        }

        public Criteria andIdsourcechapterGreaterThan(Integer value) {
            addCriterion("idsourcechapter >", value, "idsourcechapter");
            return (Criteria) this;
        }

        public Criteria andIdsourcechapterGreaterThanOrEqualTo(Integer value) {
            addCriterion("idsourcechapter >=", value, "idsourcechapter");
            return (Criteria) this;
        }

        public Criteria andIdsourcechapterLessThan(Integer value) {
            addCriterion("idsourcechapter <", value, "idsourcechapter");
            return (Criteria) this;
        }

        public Criteria andIdsourcechapterLessThanOrEqualTo(Integer value) {
            addCriterion("idsourcechapter <=", value, "idsourcechapter");
            return (Criteria) this;
        }

        public Criteria andIdsourcechapterIn(List<Integer> values) {
            addCriterion("idsourcechapter in", values, "idsourcechapter");
            return (Criteria) this;
        }

        public Criteria andIdsourcechapterNotIn(List<Integer> values) {
            addCriterion("idsourcechapter not in", values, "idsourcechapter");
            return (Criteria) this;
        }

        public Criteria andIdsourcechapterBetween(Integer value1, Integer value2) {
            addCriterion("idsourcechapter between", value1, value2, "idsourcechapter");
            return (Criteria) this;
        }

        public Criteria andIdsourcechapterNotBetween(Integer value1, Integer value2) {
            addCriterion("idsourcechapter not between", value1, value2, "idsourcechapter");
            return (Criteria) this;
        }

        public Criteria andSourcechapternameIsNull() {
            addCriterion("sourcechaptername is null");
            return (Criteria) this;
        }

        public Criteria andSourcechapternameIsNotNull() {
            addCriterion("sourcechaptername is not null");
            return (Criteria) this;
        }

        public Criteria andSourcechapternameEqualTo(String value) {
            addCriterion("sourcechaptername =", value, "sourcechaptername");
            return (Criteria) this;
        }

        public Criteria andSourcechapternameNotEqualTo(String value) {
            addCriterion("sourcechaptername <>", value, "sourcechaptername");
            return (Criteria) this;
        }

        public Criteria andSourcechapternameGreaterThan(String value) {
            addCriterion("sourcechaptername >", value, "sourcechaptername");
            return (Criteria) this;
        }

        public Criteria andSourcechapternameGreaterThanOrEqualTo(String value) {
            addCriterion("sourcechaptername >=", value, "sourcechaptername");
            return (Criteria) this;
        }

        public Criteria andSourcechapternameLessThan(String value) {
            addCriterion("sourcechaptername <", value, "sourcechaptername");
            return (Criteria) this;
        }

        public Criteria andSourcechapternameLessThanOrEqualTo(String value) {
            addCriterion("sourcechaptername <=", value, "sourcechaptername");
            return (Criteria) this;
        }

        public Criteria andSourcechapternameLike(String value) {
            addCriterion("sourcechaptername like", value, "sourcechaptername");
            return (Criteria) this;
        }

        public Criteria andSourcechapternameNotLike(String value) {
            addCriterion("sourcechaptername not like", value, "sourcechaptername");
            return (Criteria) this;
        }

        public Criteria andSourcechapternameIn(List<String> values) {
            addCriterion("sourcechaptername in", values, "sourcechaptername");
            return (Criteria) this;
        }

        public Criteria andSourcechapternameNotIn(List<String> values) {
            addCriterion("sourcechaptername not in", values, "sourcechaptername");
            return (Criteria) this;
        }

        public Criteria andSourcechapternameBetween(String value1, String value2) {
            addCriterion("sourcechaptername between", value1, value2, "sourcechaptername");
            return (Criteria) this;
        }

        public Criteria andSourcechapternameNotBetween(String value1, String value2) {
            addCriterion("sourcechaptername not between", value1, value2, "sourcechaptername");
            return (Criteria) this;
        }

        public Criteria andSourcechapterindexIsNull() {
            addCriterion("sourcechapterindex is null");
            return (Criteria) this;
        }

        public Criteria andSourcechapterindexIsNotNull() {
            addCriterion("sourcechapterindex is not null");
            return (Criteria) this;
        }

        public Criteria andSourcechapterindexEqualTo(Integer value) {
            addCriterion("sourcechapterindex =", value, "sourcechapterindex");
            return (Criteria) this;
        }

        public Criteria andSourcechapterindexNotEqualTo(Integer value) {
            addCriterion("sourcechapterindex <>", value, "sourcechapterindex");
            return (Criteria) this;
        }

        public Criteria andSourcechapterindexGreaterThan(Integer value) {
            addCriterion("sourcechapterindex >", value, "sourcechapterindex");
            return (Criteria) this;
        }

        public Criteria andSourcechapterindexGreaterThanOrEqualTo(Integer value) {
            addCriterion("sourcechapterindex >=", value, "sourcechapterindex");
            return (Criteria) this;
        }

        public Criteria andSourcechapterindexLessThan(Integer value) {
            addCriterion("sourcechapterindex <", value, "sourcechapterindex");
            return (Criteria) this;
        }

        public Criteria andSourcechapterindexLessThanOrEqualTo(Integer value) {
            addCriterion("sourcechapterindex <=", value, "sourcechapterindex");
            return (Criteria) this;
        }

        public Criteria andSourcechapterindexIn(List<Integer> values) {
            addCriterion("sourcechapterindex in", values, "sourcechapterindex");
            return (Criteria) this;
        }

        public Criteria andSourcechapterindexNotIn(List<Integer> values) {
            addCriterion("sourcechapterindex not in", values, "sourcechapterindex");
            return (Criteria) this;
        }

        public Criteria andSourcechapterindexBetween(Integer value1, Integer value2) {
            addCriterion("sourcechapterindex between", value1, value2, "sourcechapterindex");
            return (Criteria) this;
        }

        public Criteria andSourcechapterindexNotBetween(Integer value1, Integer value2) {
            addCriterion("sourcechapterindex not between", value1, value2, "sourcechapterindex");
            return (Criteria) this;
        }

        public Criteria andSourceidIsNull() {
            addCriterion("sourceid is null");
            return (Criteria) this;
        }

        public Criteria andSourceidIsNotNull() {
            addCriterion("sourceid is not null");
            return (Criteria) this;
        }

        public Criteria andSourceidEqualTo(Integer value) {
            addCriterion("sourceid =", value, "sourceid");
            return (Criteria) this;
        }

        public Criteria andSourceidNotEqualTo(Integer value) {
            addCriterion("sourceid <>", value, "sourceid");
            return (Criteria) this;
        }

        public Criteria andSourceidGreaterThan(Integer value) {
            addCriterion("sourceid >", value, "sourceid");
            return (Criteria) this;
        }

        public Criteria andSourceidGreaterThanOrEqualTo(Integer value) {
            addCriterion("sourceid >=", value, "sourceid");
            return (Criteria) this;
        }

        public Criteria andSourceidLessThan(Integer value) {
            addCriterion("sourceid <", value, "sourceid");
            return (Criteria) this;
        }

        public Criteria andSourceidLessThanOrEqualTo(Integer value) {
            addCriterion("sourceid <=", value, "sourceid");
            return (Criteria) this;
        }

        public Criteria andSourceidIn(List<Integer> values) {
            addCriterion("sourceid in", values, "sourceid");
            return (Criteria) this;
        }

        public Criteria andSourceidNotIn(List<Integer> values) {
            addCriterion("sourceid not in", values, "sourceid");
            return (Criteria) this;
        }

        public Criteria andSourceidBetween(Integer value1, Integer value2) {
            addCriterion("sourceid between", value1, value2, "sourceid");
            return (Criteria) this;
        }

        public Criteria andSourceidNotBetween(Integer value1, Integer value2) {
            addCriterion("sourceid not between", value1, value2, "sourceid");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sourcechapter
     *
     * @mbg.generated do_not_delete_during_merge Fri May 11 21:27:43 CST 2018
     */
    public static class Criteria extends GeneratedCriteria implements Serializable {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sourcechapter
     *
     * @mbg.generated Fri May 11 21:27:43 CST 2018
     */
    public static class Criterion implements Serializable {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}