package com.hhips.dao.model.problem;

import java.io.Serializable;

public class Source implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column source.idsource
     *
     * @mbg.generated Fri May 11 21:27:43 CST 2018
     */
    private Integer idsource;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column source.sourcename
     *
     * @mbg.generated Fri May 11 21:27:43 CST 2018
     */
    private String sourcename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table source
     *
     * @mbg.generated Fri May 11 21:27:43 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column source.idsource
     *
     * @return the value of source.idsource
     *
     * @mbg.generated Fri May 11 21:27:43 CST 2018
     */
    public Integer getIdsource() {
        return idsource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column source.idsource
     *
     * @param idsource the value for source.idsource
     *
     * @mbg.generated Fri May 11 21:27:43 CST 2018
     */
    public void setIdsource(Integer idsource) {
        this.idsource = idsource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column source.sourcename
     *
     * @return the value of source.sourcename
     *
     * @mbg.generated Fri May 11 21:27:43 CST 2018
     */
    public String getSourcename() {
        return sourcename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column source.sourcename
     *
     * @param sourcename the value for source.sourcename
     *
     * @mbg.generated Fri May 11 21:27:43 CST 2018
     */
    public void setSourcename(String sourcename) {
        this.sourcename = sourcename == null ? null : sourcename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table source
     *
     * @mbg.generated Fri May 11 21:27:43 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", idsource=").append(idsource);
        sb.append(", sourcename=").append(sourcename);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}