package com.hhips.dao.model.problem;

import java.io.Serializable;
import java.util.Date;

public class Work implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work.idwork
     *
     * @mbg.generated Mon Apr 30 14:26:05 CST 2018
     */
    private Integer idwork;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work.workdate
     *
     * @mbg.generated Mon Apr 30 14:26:05 CST 2018
     */
    private Date workdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work.idproblem
     *
     * @mbg.generated Mon Apr 30 14:26:05 CST 2018
     */
    private Integer idproblem;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work.usedtime
     *
     * @mbg.generated Mon Apr 30 14:26:05 CST 2018
     */
    private Integer usedtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work.workdetail
     *
     * @mbg.generated Mon Apr 30 14:26:05 CST 2018
     */
    private String workdetail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work.workmark
     *
     * @mbg.generated Mon Apr 30 14:26:05 CST 2018
     */
    private Integer workmark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work.reason
     *
     * @mbg.generated Mon Apr 30 14:26:05 CST 2018
     */
    private Integer reason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table work
     *
     * @mbg.generated Mon Apr 30 14:26:05 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work.idwork
     *
     * @return the value of work.idwork
     *
     * @mbg.generated Mon Apr 30 14:26:05 CST 2018
     */
    public Integer getIdwork() {
        return idwork;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work.idwork
     *
     * @param idwork the value for work.idwork
     *
     * @mbg.generated Mon Apr 30 14:26:05 CST 2018
     */
    public void setIdwork(Integer idwork) {
        this.idwork = idwork;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work.workdate
     *
     * @return the value of work.workdate
     *
     * @mbg.generated Mon Apr 30 14:26:05 CST 2018
     */
    public Date getWorkdate() {
        return workdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work.workdate
     *
     * @param workdate the value for work.workdate
     *
     * @mbg.generated Mon Apr 30 14:26:05 CST 2018
     */
    public void setWorkdate(Date workdate) {
        this.workdate = workdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work.idproblem
     *
     * @return the value of work.idproblem
     *
     * @mbg.generated Mon Apr 30 14:26:05 CST 2018
     */
    public Integer getIdproblem() {
        return idproblem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work.idproblem
     *
     * @param idproblem the value for work.idproblem
     *
     * @mbg.generated Mon Apr 30 14:26:05 CST 2018
     */
    public void setIdproblem(Integer idproblem) {
        this.idproblem = idproblem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work.usedtime
     *
     * @return the value of work.usedtime
     *
     * @mbg.generated Mon Apr 30 14:26:05 CST 2018
     */
    public Integer getUsedtime() {
        return usedtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work.usedtime
     *
     * @param usedtime the value for work.usedtime
     *
     * @mbg.generated Mon Apr 30 14:26:05 CST 2018
     */
    public void setUsedtime(Integer usedtime) {
        this.usedtime = usedtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work.workdetail
     *
     * @return the value of work.workdetail
     *
     * @mbg.generated Mon Apr 30 14:26:05 CST 2018
     */
    public String getWorkdetail() {
        return workdetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work.workdetail
     *
     * @param workdetail the value for work.workdetail
     *
     * @mbg.generated Mon Apr 30 14:26:05 CST 2018
     */
    public void setWorkdetail(String workdetail) {
        this.workdetail = workdetail == null ? null : workdetail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work.workmark
     *
     * @return the value of work.workmark
     *
     * @mbg.generated Mon Apr 30 14:26:05 CST 2018
     */
    public Integer getWorkmark() {
        return workmark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work.workmark
     *
     * @param workmark the value for work.workmark
     *
     * @mbg.generated Mon Apr 30 14:26:05 CST 2018
     */
    public void setWorkmark(Integer workmark) {
        this.workmark = workmark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work.reason
     *
     * @return the value of work.reason
     *
     * @mbg.generated Mon Apr 30 14:26:05 CST 2018
     */
    public Integer getReason() {
        return reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work.reason
     *
     * @param reason the value for work.reason
     *
     * @mbg.generated Mon Apr 30 14:26:05 CST 2018
     */
    public void setReason(Integer reason) {
        this.reason = reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work
     *
     * @mbg.generated Mon Apr 30 14:26:05 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", idwork=").append(idwork);
        sb.append(", workdate=").append(workdate);
        sb.append(", idproblem=").append(idproblem);
        sb.append(", usedtime=").append(usedtime);
        sb.append(", workdetail=").append(workdetail);
        sb.append(", workmark=").append(workmark);
        sb.append(", reason=").append(reason);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}